import { Category, Product, ValueProp } from './types';

export const VALUE_PROPS: ValueProp[] = [
  {
    id: '1',
    title: 'Certified Quality',
    subtitle: 'Industry standard compliance',
    icon: 'shield',
  },
  {
    id: '2',
    title: 'Fast Processing',
    subtitle: 'Quick quote turnarounds',
    icon: 'zap',
  },
  {
    id: '3',
    title: 'Expert Support',
    subtitle: 'Technical guidance & calibration',
    icon: 'award',
  },
];

export const CATEGORIES: Category[] = [
  {
    id: 'cleaning',
    name: 'Cleaning',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    itemCount: 24,
    description: 'Professional optical fiber connector cleaning kits, cassette cleaners, and lint-free wipes.',
  },
  {
    id: 'misc-accessories',
    name: 'Misc Accessories',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    itemCount: 56,
    description: 'Adapters, fiber optic patch cords, attenuators, and precision connection hardware.',
  },
  {
    id: 'thermal-strippers',
    name: 'Thermal Strippers',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    itemCount: 12,
    description: 'High-precision heated strippers designed for ribbon and single optical fiber coatings.',
  },
  {
    id: 'strippers',
    name: 'Strippers',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    itemCount: 18,
    description: 'Ergonomic tri-hole and double-hole optical fiber jacket and buffer strippers.',
  },
  {
    id: 'fst-12',
    name: 'FST-12 Fiber Separation Tool',
    image: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=800&q=80',
    itemCount: 8,
    description: 'Specialized 12-fiber ribbon separation and organizer precision tools.',
  },
  {
    id: 'ribbon-tools',
    name: 'Ribbon Fiber Tools',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    itemCount: 15,
    description: 'Comprehensive ribbon optical fiber splicing preparation and forming equipment.',
  },
  {
    id: 'cleavers',
    name: 'Cleavers',
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    itemCount: 22,
    description: 'Ultra-accurate optical fiber cleavers with auto blade rotation and scrap collectors.',
  },
  {
    id: 'fujikura-90s',
    name: 'Fujikura 90S+ Fusion Splicer',
    image: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=800&q=80',
    itemCount: 10,
    description: 'Industry flagship core-alignment fusion splicer with automated wind protector and sheath clamps.',
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 'fujikura-90s-plus',
    name: 'Fujikura 90S+ Fusion Splicer',
    category: 'Fujikura 90S+ Fusion Splicer',
    brand: 'Fujikura',
    subtitle: 'Core Alignment Fusion Splicer',
    description: 'The Fujikura 90S+ is the market-leading core-alignment fusion splicer equipped with Active Fusion Control technology, reducing loss and rework time in mission-critical telecommunications networks.',
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      'Core Alignment Splicing Technology',
      'Automated Wind Protector & Heater',
      'Active Fusion Control & Blade Management',
      'High capacity Li-ion battery (approx. 300 splices)',
    ],
    techSpecs: [
      { label: 'Fiber Alignment Method', value: 'Active Core Alignment (PAS)' },
      { label: 'Applicable Fibers', value: 'SM (ITU-T G.652/657), MM, DS, NZDS, BIF' },
      { label: 'Typical Splice Loss', value: '0.02 dB (SM), 0.01 dB (MM), 0.04 dB (DS)' },
      { label: 'Splice Time', value: '7 to 9 seconds (SM G652 Quick Mode)' },
      { label: 'Tube Heating Time', value: '9 to 13 seconds (Slim 60mm sleeve)' },
      { label: 'Electrode Life', value: '5,000 arc discharges' },
      { label: 'Magnification & Display', value: '380X (X or Y view), 5.0-inch Color Touch LCD' },
      { label: 'Battery Capacity', value: 'Approx. 300 splice & heat cycles (BTR-15)' },
      { label: 'Wireless Connectivity', value: 'Bluetooth 4.1 LE' },
      { label: 'Dimensions & Weight', value: '170 x 173 x 150 mm, 2.8 kg (with battery)' },
    ],
    features: [
      'Active Fusion Control Technology that analyzes fiber cleave end-face condition in real time',
      'Automated open/close wind protector and automated tube heater clamshells',
      'Wireless Bluetooth management with up to two CT50 fiber cleavers simultaneously',
      'Redesigned multifunctional ruggedized transit carrying case with built-in detachable work tray',
      'Field-replaceable electrode system without requiring screwdrivers or specialized tools',
    ],
    inTheBox: [
      'Fujikura 90S+ Core Alignment Fusion Splicer',
      'BTR-15 Rechargeable Lithium-ion Battery Pack',
      'ADC-20 AC Power Adapter & Cord',
      'ELCT2-16B Spare Electrodes (Pair)',
      'CC-39 Heavy Duty Hard Transit Carrying Case',
      'WT-39 Integrated Detachable Work Tray',
      'USB Cable, Alcohol Dispenser, Quick Reference Guide',
    ],
  },
  {
    id: 'sumitomo-t72c-plus',
    name: 'Sumitomo T-72C+ Fusion Splicer',
    category: 'Splicers Single Fiber',
    brand: 'Sumitomo',
    subtitle: 'High Definition Core Aligning Splicer',
    description: 'Sumitomo T-72C+ delivers ultra-high-speed splicing with an independent dual heater system, NanoTune AI precision alignment, and drop-proof construction.',
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      '5-second splice time in Quick mode',
      'Dual independent heating ovens',
      'High resolution touch screen display',
      'NanoTune technology for optimized splicing',
    ],
    techSpecs: [
      { label: 'Fiber Alignment', value: 'High-Definition Core Alignment' },
      { label: 'Splice Time', value: '5 seconds (SM Quick Mode)' },
      { label: 'Heater Cycle Time', value: '8 seconds (Slim 60mm) Dual Oven' },
      { label: 'Splice Loss', value: '0.01 dB (SM), 0.01 dB (MM)' },
      { label: 'Display', value: '5.0-inch Color Touch Screen with Anti-Glare' },
      { label: 'Electrode Life', value: '6,000 splices' },
      { label: 'Battery Capacity', value: '320 cycles (Splice & Heat)' },
      { label: 'Protection Rating', value: 'IP52 Dust/Water Resistance, 76cm drop proof' },
    ],
    features: [
      'NanoTune AI algorithms for splicing poorly prepared or dirty fibers',
      'Independent Dual Oven system speeds up production throughput by over 40%',
      'Smartphone-like intuitive capacitive touchscreen interface with pinch-to-zoom',
      'SumiCloud connected maintenance and fleet tracking platform',
    ],
    inTheBox: [
      'Sumitomo T-72C+ Fusion Splicer Unit',
      'BU-16 High-Capacity Battery Pack',
      'ADC-16 AC Adapter & Charger',
      'ER-10 Spare Electrodes',
      'Carrying Case with Working Table Platform',
      'Hand Strap and Cooling Tray',
    ],
  },
  {
    id: 'ct50-fiber-cleaver',
    name: 'CT50 Fiber Cleaver',
    category: 'Cleavers',
    brand: 'Fujikura',
    subtitle: 'High Precision Fiber Cleaver',
    description: 'Fujikura CT50 is a heavy-duty single and ribbon fiber cleaver featuring automated wireless Bluetooth blade rotation and extreme drop resistance.',
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      'Automatic blade rotation via Bluetooth',
      'Cleave angle < 0.5 degrees',
      'Single action cleave with scrap collector',
      'Impact resistant housing',
    ],
    techSpecs: [
      { label: 'Applicable Fiber', value: 'Silica optical fiber, Single to 12-fiber ribbon' },
      { label: 'Cladding Diameter', value: '125 µm' },
      { label: 'Cleaving Length', value: '5 to 20 mm (Coating 250µm - 900µm)' },
      { label: 'Typical Cleave Angle', value: '0.5 degrees or less' },
      { label: 'Blade Lifetime', value: '60,000 cleaves (16 positions x 3 heights x 1,250)' },
      { label: 'Drop Resistance', value: 'Impact resistant up to 76 cm all directions' },
      { label: 'Dimensions & Weight', value: '120 x 95 x 58 mm, 320 g' },
    ],
    features: [
      'Motorized blade rotation controlled automatically through Bluetooth link to 90S+ splicer',
      'Wide lever opening angle allows effortless fiber placement and observation',
      'One-step operation including automated fiber scrap collection bin',
      'User-replaceable blade and fiber clamp arm pads without sending for service',
    ],
    inTheBox: [
      'Fujikura CT50 Precision Cleaver Unit',
      'CB-08 Circular Blade (Pre-installed)',
      'FDB-05 Fiber Scrap Collector Box',
      'Hexagonal Wrench Tool',
      'Protective Hard Shell Case (CC-37)',
      'Instruction Manual',
    ],
  },
  {
    id: 'fip-400b-inspection-probe',
    name: 'FIP-400B Inspection Probe',
    category: 'Cleaning',
    brand: 'Afinbo',
    subtitle: 'Fiber Inspection Probe',
    description: 'Fully automated fiber end-face inspection probe with one-step pass/fail certification according to international IEC standards.',
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: [
      'Auto-centering and auto-focusing',
      'Pass/Fail automated inspection',
      'Compatible with PC and Android devices',
      'Supports LC, SC, FC, and MPO connectors',
    ],
    techSpecs: [
      { label: 'Optical Magnification', value: 'Low: 300X, High: 900X' },
      { label: 'Resolution', value: '0.55 µm detection capability' },
      { label: 'Inspection Standard', value: 'IEC 61300-3-35 Ed. 1 & Ed. 2' },
      { label: 'Automation', value: 'Auto-centering, auto-focus, auto-capture & auto-analysis' },
      { label: 'Connectivity', value: 'USB 2.0 / WiFi Adapter support' },
      { label: 'Connector Tips', value: 'Interchangeable bulkheads & patch cord adapters' },
    ],
    features: [
      '100% automated test workflow takes less than 7 seconds per connector face',
      'PDF inspection report generator with crystal clear zone-by-zone visual overlays',
      'Pristine optics with scratch and defect identification down to 1 micrometer',
      'Ergonomic trigger button for left- and right-handed operation in patch panels',
    ],
    inTheBox: [
      'FIP-400B High Resolution Digital Video Probe',
      'FC/SC Bulkhead Adapter Tip (FIPT-400-FC-SC)',
      'Universal 2.5mm Patchcord Tip (FIPT-400-U25M)',
      'Universal 1.25mm Patchcord Tip for LC (FIPT-400-U12M)',
      'Software & Certification Suite, Protective Pouch',
    ],
  },
  {
    id: 'inno-view-7',
    name: 'INNO View 7 Fusion Splicer',
    category: 'Splicers Ribbon Fiber',
    brand: 'INNO',
    subtitle: 'Ultra-High Magnification Splicer',
    description: 'High performance core alignment splicer with world-leading 520x optical magnification and a massive 5-inch high-resolution touchscreen.',
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: ['520X Magnification', 'Fast Heating Time', 'Rugged Rubberized Bumper'],
    techSpecs: [
      { label: 'Magnification', value: '520X for X or Y single view, 260X for dual view' },
      { label: 'Splicing Time', value: '7 seconds (Quick Mode)' },
      { label: 'Heating Time', value: '13 seconds' },
      { label: 'Battery Capacity', value: '9800mAh (355 splice & heat cycles)' },
      { label: 'Display', value: '5.0-inch High Resolution Color LCD Touch' },
      { label: 'Illumination', value: '3 Ultra-bright White LEDs for night work' },
    ],
    features: [
      'Highest magnification ratio in the industry (520X) for microscopic fiber inspection',
      'Double tapping on the screen allows 520X instant zoom into core alignment area',
      'Ultra-high capacity 9800mAh battery delivers over 355 consecutive splices',
    ],
    inTheBox: [
      'INNO View 7 Fusion Splicer',
      'V7 Precision Fiber Cleaver',
      'High Capacity Battery Pack (LBT-30)',
      'AC Adapter & Power Cord',
      'Hard Carrying Case & Shoulder Strap',
    ],
  },
  {
    id: 'nyfors-autocleave',
    name: 'Nyfors AutoCleave LDF',
    category: 'Cleavers',
    brand: 'Nyfors',
    subtitle: 'Large Diameter Fiber Cleaver',
    description: 'High precision tension-and-scribe cleaving system designed specifically for large diameter and specialty optical fibers up to 1000 µm.',
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: ['Tension & Scribe technology', 'Programmable cleaving parameters'],
    techSpecs: [
      { label: 'Cladding Diameter Range', value: '125 µm to 1000 µm' },
      { label: 'Cleave Angle', value: '< 0.3° typical on 125µm fiber, < 0.5° on 400µm' },
      { label: 'Tension System', value: 'Microprocessor controlled linear pull mechanism' },
      { label: 'Blade Mechanism', value: 'Diamond blade with automated microscopic scribe' },
      { label: 'Interface', value: 'PC software control + standalone keypad presets' },
    ],
    features: [
      'Tension-and-scribe method eliminates glass damage and burrs across specialty fibers',
      'Fully programmable clamping force, tension load, and diamond blade penetration speed',
      'Engineered for R&D laboratories, optical sensor production, and high-power fiber lasers',
    ],
    inTheBox: [
      'AutoCleave LDF Base Cleaving Unit',
      'Precision Diamond Scribe Assembly',
      'Fiber Clamping Inserts Set',
      'Universal Power Supply and Calibration Block',
    ],
  },
  {
    id: 'fitel-s179',
    name: 'Fitel S179 Core Alignment',
    category: 'Splicers Single Fiber',
    brand: 'Fitel',
    subtitle: 'Handheld Core Alignment Splicer',
    description: 'Compact, ruggedized core-alignment fusion splicer with fast 6-second splice cycle, high drop tolerance, and canopy illumination.',
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: ['6-second fast splice', '4.3-inch touchscreen LCD'],
    techSpecs: [
      { label: 'Alignment Method', value: 'Core Alignment with 4 Motors' },
      { label: 'Splice Time', value: '6 seconds (Semi-auto mode)' },
      { label: 'Heating Time', value: '9 seconds (Power mode)' },
      { label: 'Environmental Resistance', value: 'IP52, IK07 Shock Proof, Drop proof 76cm' },
      { label: 'Lighting', value: '3+1 LED lighting wide chamber illumination' },
    ],
    features: [
      '4.3-inch responsive touchscreen with intuitive graphical navigation',
      'Illuminated V-groove workspace with 4 powerful LEDs for low-light maintenance',
      'High-torque motor system handles bent and curved drop cables with ease',
    ],
    inTheBox: [
      'Fitel S179 Fusion Splicer Unit',
      'Rechargeable Battery Pack (S947A)',
      'AC Adapter & Power Cord',
      'Hard Carrying Case & Fiber Stripper',
    ],
  },
  {
    id: 'afinbo-fst12-separating-tool',
    name: 'AFINBO FST-12 Ribbon Separation',
    category: 'FST-12 Fiber Separation Tool',
    brand: 'Afinbo',
    subtitle: 'Precision 12-Fiber Ribbon Separator',
    description: 'Professional 12-fiber optical ribbon splitting and separation tool for clean, damage-free segregation into individual fibers or pairs in seconds.',
    isBestSeller: false,
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80',
    ],
    specs: ['Splits up to 12 fibers effortlessly', 'Precision alignment teeth'],
    techSpecs: [
      { label: 'Fiber Ribbon Capacity', value: '2 to 12 fiber ribbons' },
      { label: 'Fiber Pitch', value: '250 µm standard ribbon matrix' },
      { label: 'Separation Types', value: 'Individual single fibers, 2x6, 3x4, 4x3 ribbon subsets' },
      { label: 'Material Body', value: 'Anodized hardened aircraft aluminum alloy' },
      { label: 'Dimensions & Weight', value: '115 x 38 x 24 mm, 140 g' },
    ],
    features: [
      'Micro-machined ceramic guidance channels prevent coating delamination or glass stress',
      'Enables fast single fiber routing in breakout splice trays and compact closures',
      'Requires zero blade calibration or electric power in field conditions',
    ],
    inTheBox: [
      'AFINBO FST-12 Ribbon Separator Tool',
      'Precision Fiber Guide Plate',
      'Hard Protective Storage Case',
      'Operator Quick Start Card',
    ],
  },
];
